name: Publish
on:
  push:
    branches:
      - "master"
jobs:
  build:
    name: Publish Docker Container
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Publish Image
        run: |
          export REPO=ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          docker pull $REPO:latest
          docker build -t $REPO:$VERSION -t $REPO:latest .
          docker push $REPO:$VERSION
          docker push $REPO:latest
        env:
          VERSION: ${{ steps.version.outputs.version }}
